name: Ievasnotes
favicon: null
layout_spectrum: 0.25936
typography_spectrum: 0.14107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: Netherlands Utrecht Bilthoven Ieva
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#131514'
    - '#475152'
    - '#807e69'
    - '#e3d6a2'
  brandStrength: 0.5625
  lightness: 0.925911602564156
  saturation: 0.125
  rhythmicContrast: 0.38207543827593327
purpose: []
